# Numpy

- <b> numpy--- is a library <b>

- <b>numpy--- numerical python <b>
    
- <b>imp concept is array <b
    
- <b> numpy is homogeneous <b>
    
- <b> use of numpy --- scientific,statistics,research,AI, data creation <b>

- <b>numpy ndarray---- nd means n dimensional <b>
    
- <b> array ---- collection of similar  items <b>

In [36]:
import numpy as np # alias

In [37]:
x=np.array([12,23,34])
print(x)

[12 23 34]


In [38]:
type(x)

numpy.ndarray

- <b> one float number it will change all elements into float <b>
- <b>if one of the element is float the complete array element in float <b>

In [40]:
x=np.array([12,23.4,67])  
print(x)

[12.  23.4 67. ]


- <b>if we do add a string element in a list of integer it will covert all element into string <b>

In [42]:
x=np.array([12,"a",90])
print(x)           

['12' 'a' '90']


- <b> if we have a string or float in a list it will convert the data into string. this is known as upcasting<b>

In [44]:
x=np.array([12.3,"a",34])
print(x)

['12.3' 'a' '34']


# Upcasting

-<b>str (1st priority) <b>

-<b> float (2nd priority) <b>

-<b>int  (3rd priority) <b>

# Accessing of 2d array

In [48]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[23,34,56,78,43]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [23, 34, 56, 78, 43]])

<b> [:,:] -- 1st slice represent row (start:end)  and 2nd representr column (start:end) <b>

In [50]:
x[2:4,0:4]

array([[11, 12, 13, 14],
       [16, 17, 18, 19]])

# 2d array

In [52]:
x=np.array([[12,34],[45,67]])
print(x)

[[12 34]
 [45 67]]


In [53]:
x.ndim   #number of dimention (shortfrom count the bracket tell the dimention)

2

In [54]:
x=np.array([[[12,34,78],[56,78,5.6],[78,56,34]]])
print(x)

[[[12.  34.  78. ]
  [56.  78.   5.6]
  [78.  56.  34. ]]]


In [55]:
x=np.array([[[12,34,78],[56,78,56],[78,56,34]]])
print(x)

[[[12 34 78]
  [56 78 56]
  [78 56 34]]]


In [56]:
b=np.array([[12,34],[67,78],[90,9]])
print(b)

[[12 34]
 [67 78]
 [90  9]]


# Shape

- <b> return the number of rows and columns  <b>

- <b> if we want to kn about row and columns with the help of shape we will get to know <b>

In [60]:
z=np.array([[12,23],[67,78],[56,67]])
z.shape

(3, 2)

- <b> we can also change the shape of the element (arrange the element) <b>

In [62]:
z.shape=(2,3)
z

array([[12, 23, 67],
       [78, 56, 67]])

# Reshape

-  <b> it is use to rearange the array element in desired shape <b>

In [65]:
x=np.array([[23,45,67],[89,90,9]])  #2,3
print(x)
print()   # for space
y=x.reshape(3,2)
y


[[23 45 67]
 [89 90  9]]



array([[23, 45],
       [67, 89],
       [90,  9]])

In [66]:
x=np.array([12,23,45,46,78,90,78,6,56,44])
x.shape #bcs it is 1d array so it will return only the number of element

(10,)

# Zeros function

- <b> it is used to create array with all elements as zero <b>

In [69]:
x=np.zeros(5)   #by default float value
x      

array([0., 0., 0., 0., 0.])

In [70]:
x=np.zeros(5,dtype=int)  #by defauly float
x

array([0, 0, 0, 0, 0])

In [71]:
x=np.zeros((5,5),dtype=int)  #by default float
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Ones function

- <b> it is used to generate array of all ones <b>

In [74]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

 <b> want to convert into int <b>

In [76]:
x=np.ones(5,dtype=int)
x

array([1, 1, 1, 1, 1])

 <b> want to covert into matrix <b>

In [78]:
x=np.ones((5,5),dtype=int)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [79]:
#there will be any no 5 or any
x=5*np.ones((5,5),dtype=int)
x

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

# Arange

-  <b>array of range <b>

# 1d array

In [83]:
x=np.arange(30)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

- <b> This functionns returns an ndarray object containing evenly shaped values with <b>


In [85]:
x=np.arange(10,20)
x


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [86]:
x=np.arange(10,20,2)
x

array([10, 12, 14, 16, 18])

# 2d array 

In [88]:
x=np.arange(30).reshape(6,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

# linspace

- <b> start end--- how many elements---- evenly space <b>

In [91]:
#10-20----- 10,12.4,15.5,17.5,20.0  find the common number like 10 reserve hogya uske baad 4 sapce bache to 10 ko 4 se 
#divide krdo jo ans aayga usko 10 m add krdo talki 20 ans aajay
z=np.linspace(10,20,5)
z

array([10. , 12.5, 15. , 17.5, 20. ])

<b>if we do not want to get the last /end value <b>

In [93]:
z=np.linspace(10,20,5,endpoint=False)
z

array([10., 12., 14., 16., 18.])

# 3d array

In [94]:
x=np.arange(27).reshape(3,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [95]:
x=np.arange(30).reshape(3,5,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [96]:
x=np.arange(30).reshape(3,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


# Matrix operations

 <b> sum of two matrix <b>

In [97]:
x=np.array([[12,33,45],[67,89,71],[1,2,3]])
print(x)
print()
y=np.array([[3,2,1],[4,5,6],[7,8,9]])
print(y)
print()
z=x+y
print(z)

[[12 33 45]
 [67 89 71]
 [ 1  2  3]]

[[3 2 1]
 [4 5 6]
 [7 8 9]]

[[15 35 46]
 [71 94 77]
 [ 8 10 12]]


# Transpose of matrix

<b> convert row to column <b>

In [98]:
x=np.array([[12,23,45,56],[78,89,90,67]])
print(x)
print()
print(np.transpose(x))

[[12 23 45 56]
 [78 89 90 67]]

[[12 78]
 [23 89]
 [45 90]
 [56 67]]


In [99]:
x=np.array([[12,23,45,56],[78,89,90,67]])
print(x)
print()
np.transpose(x)

[[12 23 45 56]
 [78 89 90 67]]



array([[12, 78],
       [23, 89],
       [45, 90],
       [56, 67]])

# Multiplication of  matrix

<b> if 1st column of first matrix is not equal to another one then multiplication is not possiblle <b>

In [100]:
x=np.array([[1,2],[3,4]])
print(x)
print()
y=np.array([[5,1],[4,2]])
print(y)
print()
z=np.dot(x,y) #.dot is a inbuild function
print(z)

[[1 2]
 [3 4]]

[[5 1]
 [4 2]]

[[13  5]
 [31 11]]


# 2d array

In [101]:
x=np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# How to find diagonal element

In [102]:
np.diag(x)


array([ 0,  6, 12, 18, 24])

# Combining the array -- matrices


In [103]:
x=np.array([[12,23],[45,56]])
print(x)
print()
y=np.array([[89,3],[12,76]])
print(y)
print()
#hstack--- horizontal stack
print(np.hstack((x,y)))


[[12 23]
 [45 56]]

[[89  3]
 [12 76]]

[[12 23 89  3]
 [45 56 12 76]]


 <b> hstack is for horizontal stack <b>

 <b>another way <b>

In [104]:
x=np.array([[11],[12],[13]])
print(x)
print()
y=np.array([[14],[15],[16]])
print(y)
print()
print(np.hstack((x,y)))

[[11]
 [12]
 [13]]

[[14]
 [15]
 [16]]

[[11 14]
 [12 15]
 [13 16]]


In [105]:
x=np.array([[12,11,13],[14,15,16]])
print(x)
print()
y=np.array([[17,18,19],[1,2,3]])
print(y)
print()
#vstack--- vertical stack
print(np.vstack((x,y)))

[[12 11 13]
 [14 15 16]]

[[17 18 19]
 [ 1  2  3]]

[[12 11 13]
 [14 15 16]
 [17 18 19]
 [ 1  2  3]]


<b> vstack is for vertical Stack  <b>

In [263]:
#combining two matrices
x=np.array([[12,13],[14,15]])
print(x)
print()
y=np.array([[1,2],[3,4]])\

print(y)
print()
np.concatenate((x,y),axis=1) #hstack

[[12 13]
 [14 15]]

[[1 2]
 [3 4]]



array([[12, 13,  1,  2],
       [14, 15,  3,  4]])

x=np.array([[12,13],[14,15]])
print(x)
print()
y=np.array([[1,2],[3,4]])
print(y)
print()
np.concatenate((x,y),axis=0) #vstack

# Make a digonal matrix

In [108]:
x=[12,23,45,67]
y=np.diag(x)
y

array([[12,  0,  0,  0],
       [ 0, 23,  0,  0],
       [ 0,  0, 45,  0],
       [ 0,  0,  0, 67]])

# Identity matrix

In [109]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<b> identity matrix convert into int <b>

In [110]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Random number generation 

<b> integer <b>

In [111]:
x=np.random.randint(1,10)
x

5

<b> decimal number--- by default btw 0 and 1 <b> 

In [272]:
x=np.random.rand()
x

0.035671968937962095

# Generate array of random integer 

In [113]:
x=np.random.randint(100,400,10)
x

array([181, 292, 281, 199, 332, 266, 216, 197, 123, 223])

# Generate array of decimal number

In [114]:
x=np.random.rand(5)
x

array([0.14262206, 0.72457156, 0.63599346, 0.22183669, 0.68321131])

In [115]:
x=np.random.randint(100,400,(5,5))
x

array([[331, 125, 200, 328, 240],
       [399, 107, 319, 293, 362],
       [381, 275, 289, 166, 360],
       [186, 125, 360, 352, 119],
       [159, 328, 190, 231, 153]])

In [116]:
from numpy.random import randint as ri

In [117]:
x=ri(10,50,(3,3))
x

array([[45, 28, 48],
       [44, 44, 33],
       [43, 35, 30]])

# Seed 

-  <b>fix the numbers when generated <b>

In [118]:
np.random.seed(2)  #anynumber in place of 2 just to activate thus
x=ri(10,50,(3,3))
x

array([[25, 18, 32],
       [28, 21, 17],
       [44, 41, 21]])

In [119]:
np.random.seed(1)
x=ri(10,100,(5,5))
x


array([[47, 22, 82, 19, 85],
       [15, 89, 74, 26, 11],
       [86, 81, 16, 35, 60],
       [30, 28, 94, 21, 38],
       [39, 24, 60, 78, 97]])

# For horizontal sort

In [120]:
np.sort(x,axis=1)

array([[19, 22, 47, 82, 85],
       [11, 15, 26, 74, 89],
       [16, 35, 60, 81, 86],
       [21, 28, 30, 38, 94],
       [24, 39, 60, 78, 97]])

# For vertical sort

In [121]:
np.sort(x,axis=0)

array([[15, 22, 16, 19, 11],
       [30, 24, 60, 21, 38],
       [39, 28, 74, 26, 60],
       [47, 81, 82, 35, 85],
       [86, 89, 94, 78, 97]])

 <b> column <b>

In [283]:
np.max(x,axis=0)

0.035671968937962095

 <b> row <b>

In [123]:
np.max(x,axis=1)

array([85, 89, 86, 94, 97])

# Ravel

- <b> used to flat the array , it will convert rwo,column tp only row or convert 2d array into 1d array <b>

<b> imp function <b>

In [124]:
y=np.ravel(x)
y

array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11, 86, 81, 16, 35, 60, 30, 28,
       94, 21, 38, 39, 24, 60, 78, 97])

In [125]:
#interview question---- diff btw max and argmax
#argmax--- return the index of max element
np.argmax(y)


24

# Argmin

- <b> return the index of min element for 1d array <b>

In [126]:
np.argmin(y)

9

# Argmax 

- <b> return the index of the max element from 1d array <b>

In [127]:
np.argmax(y)

24

##### argmax-- return the index of min element for 1d array

In [128]:
np.argmin(y)

9

##### argmin---- return the index of max element for 2d array

In [129]:
np.argmax(x)

24

##### argmin---- return the index of min element for 2d array

In [130]:
np.argmin(x)

9

##### argmax--- return the index of max element for 2d aaray in horizontal line

In [131]:
np.argmax(x,axis=1)

array([4, 1, 0, 2, 4], dtype=int64)

In [132]:
np.argmax(x)

24

##### argmin--- return the index of min element for 2d aaray in vertical line

In [133]:
np.argmin(x,axis=0)

array([1, 0, 2, 0, 1], dtype=int64)

# Split

In [134]:
a=np.arange(12)
np.split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# Resize

In [135]:
a=np.array([[1,2,3],[4,5,6]])
np.resize(a,(3,2))


array([[1, 2],
       [3, 4],
       [5, 6]])

# Conditional selection

In [11]:
a=np.arange(1,21)
print(a)


NameError: name 'np' is not defined

In [137]:
#jha condition match hori h wha true nito false
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

<b> if we want to get the data of true elemwnts<b>

<b>if we want true condition<b>

In [138]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

<b> if we want false condition <b>

In [139]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### want to find even number

In [140]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

##### want to find odd number

In [141]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

<b>where returns index<b>

<b> condition returns value<b>

In [143]:
a=np.array([1,2,3,4,5,2])
print(a)

[1 2 3 4 5 2]


In [144]:
a.ndim

1

In [145]:
a.shape  #shape always return tuple

(6,)

# Where  

In [146]:
x=np.where(a==2)  #it will return index where 2 is lied
x


(array([1, 5], dtype=int64),)

In [147]:
np.where(a==3) #where returns only index

(array([2], dtype=int64),)

In [148]:
np.where(a<4)

(array([0, 1, 2, 5], dtype=int64),)

##### if we havea given list of random numbers/choice numbers by user

In [149]:
x=[12,22,34,56,78,98,76,44,2,22]
y=np.random.choice(x)
print(y)

44


# Linspace

- <b>it is used to devide the number in equal parts means the difference is comma<b>

In [150]:
x=np.linspace(10,20,5)
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [151]:
x=np.linspace(10,20,5,endpoint=False)
x

array([10., 12., 14., 16., 18.])

In [152]:
from numpy.random import randint as ri

In [153]:
#accessing of 2d array
#[:]--[row_range,col_range]
np.random.seed(56)
x=ri(10,90,(5,5))
x

array([[25, 74, 44, 24, 32],
       [67, 65, 34, 22, 76],
       [53, 21, 43, 20, 41],
       [38, 47, 44, 25, 38],
       [29, 79, 51, 76, 84]])

In [154]:
x[1:3,2:4]

array([[34, 22],
       [43, 20]])